name: Generate Data

on:
  push:
    branches: [main]
  workflow_dispatch:
    
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
          submodules: recursive

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Reset to main
        run: |
          git fetch origin main
          git reset --hard origin/main
          git submodule update --init --recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install script tool
        run: dotnet tool install -g dotnet-script

      - name: Run script
        run: |
          dotnet script Scripts/Main.csx generate-file-path-and-commit-history-collection Docs DocumentFilePathAndCommitHistoryCollection.json --exclude-patterns Docs/템플릿.md
          dotnet script Scripts/Main.csx generate-file-tree Docs DocumentFileTree.json --exclude-patterns Docs/템플릿.md
          dotnet script Scripts/Main.csx generate-site-map Docs DocumentSiteMap.xml https://yubiz.github.io --exclude-patterns Docs/템플릿.md

      - name: Commit Data
        run: |
          git add DocumentFilePathAndCommitHistoryCollection.json DocumentFileTree.json DocumentSiteMap.xml
          git commit -m "데이터 업데이트"

      - name: Force push
        run: git push -f
